### ISSUE TITLE
[maindetail] swiper 페이지네이션 불렛스타일 커스텀

### ISSUE THREAD

**Issue by suwan98** [like-lion-javascript-project-9/enter-euid#81]
swiper의 페이지네이션 불렛스타일을 커스텀하기위해 tawil.css에 선택자 스타일을 정의했습니다

```js
export const swiper = new Swiper('.swiper', {
  pagination: {
    el: '.swiper-pagination',
    clickable: true,
    bulletClass: 'render-bullet',
    bulletActiveClass: 'is-active',
  },
});

```

```css

tailwind.css

.render-bullet {
 background-color: #82828282;
 width: 10px;
 height: 10px;
 border-radius: 50%;
 display: inline-block;
 opacity: 1;
 margin-right: 8px;
}

.render-bullet.is-active{
  background-color: #373F67;
}


```
